version: '3.8'

volumes:
  pgdata:

networks:
  app-network:
    driver: bridge

services:
  postgres:
    container_name: postgres
    image: postgres:16
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: social_travel_trip
    ports:
      - "5433:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - app-network

  backend:
    container_name: backend
    image: ngoccuong9d/backend-app:latest
    ports:
      - "3000:3000"
    volumes:
      - ./backend/upload-v2:/app/upload-v2
    depends_on:
      - postgres
    environment:
      DATABASE_URL: postgres://postgres:postgres@postgres:5432/social_travel_trip
    networks:
      - app-network

  frontend:
    container_name: frontend
    image: ngoccuong9d/frontend-app:latest
    ports:
      - "4200:4200"
    depends_on:
      - backend
    networks:
      - app-network
