export const travelData = [
  {
    id: 1,
    title: "Hội An, Quảng Nam",
    slug: "hoi-an",
    lat: 15.8801,
    lng: 108.338,
    date: "2023-03-15",
    image: "/placeholder.svg?height=300&width=500",
    description:
      "Phố cổ Hội An là một trong những điểm đến yêu thích của tôi với những con phố đèn lồng đầy màu sắc và ẩm thực tuyệt vời.",
    category: "di sản",
    rating: 5,
    highlights: ["Phố cổ", "Đèn lồng", "Ẩm thực", "Sông Thu Bồn"],
  },
  {
    id: 2,
    title: "Vịnh Hạ Long, Quảng Ninh",
    slug: "ha-long-bay",
    lat: 20.9101,
    lng: 107.1839,
    date: "2023-05-20",
    image: "/placeholder.svg?height=300&width=500",
    description: "Vịnh Hạ Long với hàng nghìn hòn đảo đá vôi là một kỳ quan thiên nhiên thế giới không thể bỏ qua.",
    category: "biển",
    rating: 5,
    highlights: ["Đảo đá vôi", "Du thuyền", "Hang động", "Làng chài"],
  },
  {
    id: 3,
    title: "Đà Lạt, Lâm Đồng",
    slug: "da-lat",
    lat: 11.9404,
    lng: 108.4583,
    date: "2023-07-10",
    image: "/placeholder.svg?height=300&width=500",
    description: "Thành phố ngàn hoa với khí hậu mát mẻ quanh năm, là điểm đến lý tưởng để tránh cái nóng mùa hè.",
    category: "núi",
    rating: 4,
    highlights: ["Thung lũng Tình Yêu", "Hồ Xuân Hương", "Đồi Robin", "Cà phê"],
  },
  {
    id: 4,
    title: "Phú Quốc, Kiên Giang",
    slug: "phu-quoc",
    lat: 10.2231,
    lng: 103.957,
    date: "2023-09-05",
    image: "/placeholder.svg?height=300&width=500",
    description: "Hòn đảo ngọc với những bãi biển cát trắng, nước biển trong xanh và hoàng hôn tuyệt đẹp.",
    category: "biển",
    rating: 4,
    highlights: ["Bãi Sao", "Hòn Thơm", "Làng chài Hàm Ninh", "Sunset Sanato"],
  },
  {
    id: 5,
    title: "Sapa, Lào Cai",
    slug: "sapa",
    lat: 22.3364,
    lng: 103.8438,
    date: "2023-11-15",
    image: "/placeholder.svg?height=300&width=500",
    description: "Thị trấn trong mây với những thửa ruộng bậc thang tuyệt đẹp và văn hóa dân tộc đặc sắc.",
    category: "núi",
    rating: 5,
    highlights: ["Fansipan", "Ruộng bậc thang", "Thác Bạc", "Bản Cát Cát"],
  },
  {
    id: 6,
    title: "Huế, Thừa Thiên Huế",
    slug: "hue",
    lat: 16.4637,
    lng: 107.5909,
    date: "2022-12-10",
    image: "/placeholder.svg?height=300&width=500",
    description: "Cố đô Huế với hệ thống di tích lịch sử và văn hóa ẩm thực đặc sắc của triều đại nhà Nguyễn.",
    category: "di sản",
    rating: 4,
    highlights: ["Đại Nội", "Lăng Tự Đức", "Sông Hương", "Bún bò Huế"],
  },
  {
    id: 7,
    title: "Nha Trang, Khánh Hòa",
    slug: "nha-trang",
    lat: 12.2388,
    lng: 109.1967,
    date: "2022-08-20",
    image: "/placeholder.svg?height=300&width=500",
    description: "Thành phố biển sôi động với bãi biển dài, nhiều hoạt động giải trí và hải sản tươi ngon.",
    category: "biển",
    rating: 4,
    highlights: ["Vinpearl Land", "Hòn Tằm", "Tháp Bà Ponagar", "Lặn biển"],
  },
  {
    id: 8,
    title: "Mộc Châu, Sơn La",
    slug: "moc-chau",
    lat: 20.8249,
    lng: 104.7291,
    date: "2022-02-15",
    image: "/placeholder.svg?height=300&width=500",
    description: "Cao nguyên xanh mát với những đồi chè, vườn hoa và văn hóa dân tộc Thái, H'Mông đặc sắc.",
    category: "núi",
    rating: 4,
    highlights: ["Đồi chè", "Thác Dải Yếm", "Rừng thông bản Áng", "Mùa hoa cải"],
  },
  {
    id: 9,
    title: "Cần Thơ",
    slug: "can-tho",
    lat: 10.0341,
    lng: 105.7881,
    date: "2022-04-10",
    image: "/placeholder.svg?height=300&width=500",
    description: "Thành phố sông nước với chợ nổi Cái Răng nổi tiếng và ẩm thực đặc trưng vùng sông nước.",
    category: "sông nước",
    rating: 4,
    highlights: ["Chợ nổi Cái Răng", "Nhà cổ Bình Thủy", "Vườn trái cây", "Bánh cống"],
  },
  {
    id: 10,
    title: "Mũi Né, Bình Thuận",
    slug: "mui-ne",
    lat: 10.9326,
    lng: 108.2872,
    date: "2021-11-25",
    image: "/placeholder.svg?height=300&width=500",
    description: "Thiên đường resort với những đồi cát vàng, bãi biển dài và làng chài đầy màu sắc.",
    category: "biển",
    rating: 3,
    highlights: ["Đồi cát bay", "Suối Tiên", "Làng chài", "Lướt ván diều"],
  },
]
